import type {Metadata} from 'next';
import './globals.css';
import React from "react";
import {Provider} from "react-redux";
import {store} from "../store";

const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

function RootLayout({children,}: {children: React.ReactNode;}) {
    return (
        <html lang="en" className="bg-canvas-color text-white">
            <body>
                {children}
            </body>
        </html>
    );
}

export default RootLayout;
export {
    metadata,
}